 
---
- name: Install packages that allow apt to be used over HTTPS
  apt:
    state: present
    update_cache: yes
    pkg:
      - python3
      - build-essential
      - mc
      - terminator
      - curl
      - wget
      - git
      - git-gui
      - zsh
      - linuxbrew-wrapper
      - unzip
  become: true

- name: check if previious installed
  stat: 
    path: /home/vagrant/.oh-my-zsh
  register: previous_zsh_instalation

- name: Remove previous the zsh-installation
  file: path=/home/vagrant/.oh-my-zsh state=absent
  when: previous_zsh_instalation

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  register: cloning

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning
    
- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu eoan stable
    state: present
  become: true

- name: Install docker and its dependecies
  apt:
    state: present
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: true

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- name: Install microk8s
  snap:
    name:
      - microk8s
    classic: yes
  become: true

- name: Install eclipse
  snap:
    name:
      - eclipse
    classic: yes
  become: true

- name: Adds fasd repo
  apt_repository:
    repo: 'ppa:aacebedo/fasd'
    update_cache: yes
  become: true

- name: Install fasd with apt
  apt: name=fasd state=latest
  become: true

- homebrew:
    name: jesseduffield/lazygit/lazygit
    state: present
  become: false

- homebrew:
    name: jesseduffield/lazydocker/lazydocker
    state: present
  become: false

- name: Create eclipse directory if it does not exist
  file:
    path: ~/IDE/eclipse/
    state: directory
    mode: '0755'
  become: false

- name: Change shell
  shell: chsh -s /bin/zsh
