 
---
- name: Install packages that allow apt to be used over HTTPS
  apt:
    state: present
    update_cache: yes
    pkg:
      - python3
      - build-essential
      - mc
      - terminator
      - curl
      - wget
      - git
      - git-gui
      - zsh
      - linuxbrew-wrapper
      - unzip
      - fonts-powerline
      - thefuck
      - maven
      - nodejs
      - npm
      - vagrant
      - pylint
      - python3-pip
      - bat 
      - openjdk-8-jdk
      - openjdk-11-jdk
      - openjdk-13-jdk
      - openjdk-14-jdk
      
  become: true

- name: check if previious installed
  stat: 
    path: ~/.oh-my-zsh
  register: previous_zsh_instalation
  become: false

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  register: cloning
  when: previous_zsh_instalation
  become: false

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning
  become: false
    
- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu eoan stable
    state: present
  become: true

- name: Install docker and its dependecies
  apt:
    state: present
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: true

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- name: Install microk8s
  snap:
    name:
      - microk8s
    classic: yes
  become: true

- name: Install dbeaver
  snap:
    name:
      - dbeaver-ce
    classic: yes
  become: true

- name: Install eclipse
  snap:
    name:
      - eclipse
    classic: yes
  become: true

- name: Adds fasd repo
  apt_repository:
    repo: 'ppa:aacebedo/fasd'
    update_cache: yes
  become: true

- name: Install fasd with apt
  apt: name=fasd state=latest
  become: true

- name: update brew
  shell: brew update
  become: false

- name: Install lazydocker
  shell: brew install jesseduffield/lazydocker/lazydocker </dev/null
  become: false

- name: Install lazygit
  shell: brew install jesseduffield/lazygit/lazygit </dev/null
  become: false

- name: Install tig
  shell: brew install tig </dev/null
  become: false

- git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel9k

- name: Delete ~/.zshrc
  file:
    path: ~/.zshrc
    state: absent

- name: update zshrc
  get_url: 
    url: https://raw.githubusercontent.com/SalesianosZaragoza/ConfigLinuxFiles/master/.zshrc
    dest: ~/.zshrc
    mode: '0775'
  become: false

- name: Change shell
  expect:
    command: "chsh -s /bin/zsh"
    responses:
      (?i)password: "vagrant"
  become: false
  
